version: "3.9" 
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume02:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume02: {}
